### ISSUE TITLE
Orga-Security

### ISSUE THREAD

**Issue by sebastian-grabsch-pexon** [Viridia-Pexon/viridia#8]
Situation: We are vulnerable to attacks and want to secure the project

Task: Implement Security Guidelines

Action: 
* Define sane defaults for repositories
* Enforce 2FA and SSH/Passkey-Usage
* Enable Members to assign other members to tasks

- [x] 2FA
- [ ] ~SSH/Passkey-Usage~
- [x] Enable self assign by members

Result: 
* Secure Project

**Comment by martinstecher** [comment]
@waiting 
on permissions

**Comment by sebastian-grabsch-pexon** [comment]
> [waiting] on permissions

Granted.

**Comment by martinstecher** [comment]
Idea by @tom-hauschke : utilize Terraform for git config
